export default function Reviews() {
  return (
    <section className="view active" id="reviews">
<div className="page-head"><div><div className="label eyebrow">Client feedback</div><h1>Reviews</h1><p>Verified client feedback associated with completed SENM projects.</p></div></div>
<div className="metrics"><div className="metric"><div className="label muted">Average rating</div><div className="metric-value">4.9</div><div className="metric-note">out of 5</div></div><div className="metric"><div className="label muted">Verified reviews</div><div className="metric-value">42</div><div className="metric-note">SENM verified</div></div><div className="metric"><div className="label muted">5-star</div><div className="metric-value">39</div><div className="metric-note">93% of reviews</div></div><div className="metric"><div className="label muted">Response</div><div className="metric-value">100%</div><div className="metric-note">reviews responded to</div></div></div>
<div className="grid2"><div><div className="section-title"><h2>Recent reviews</h2><span>VERIFIED</span></div><div className="review"><div className="stars">★★★★★</div><h3 style={{'fontFamily': 'var(--display)', 'fontSize': '18px', 'color': 'var(--navy)', 'margin': '8px 0 0'}}>Clear, practical advice</h3><p>“James explained the structural changes clearly and kept the process moving through Building Control.”</p><div className="review-meta">Verified client · Rear extension · Islington · 2026</div></div><div className="review" style={{'marginTop': '12px'}}><div className="stars">★★★★★</div><h3 style={{'fontFamily': 'var(--display)', 'fontSize': '18px', 'color': 'var(--navy)', 'margin': '8px 0 0'}}>Exactly what we needed</h3><p>“The calculations and drawings were delivered when promised and the revisions were handled quickly.”</p><div className="review-meta">Verified client · Loft conversion · North London · 2026</div></div></div><aside><div className="rail"><div className="rail-head"><h3>Review profile</h3></div><div style={{'fontFamily': 'var(--display)', 'fontSize': '35px', 'color': 'var(--navy)', 'fontWeight': '600'}}>4.9 ★</div><p className="small">Based on 42 verified reviews.</p></div></aside></div>
</section>
  );
}
